require("dotenv").config();

const mongoose = require("mongoose");
const connectDB = require("../src/db");
const Customer = require("../src/models/customer.model");

async function run() {
    await connectDB();

    try {
        await Customer.create({
            full_name: "A",
            country_code: "+91"
        });

         await Customer.create({
            full_name: "B",
            country_code: "+91",
        });

        console.log(customer);
    } catch (err) {
        console.log(err.name);
        console.log(err.message);
    }

    await mongoose.disconnect();
}

run();

// Observations:
// Duplicate phone number throws:
// err.code = 11000
// err.name = MongoServerError
// Reason being that 'unique: true' is not a validator.It creates a MongoDB unique index,
// the error is generated by MongoDB, not Mongoosegit

//after the  removing phone_number 'required:true' it throws the same duplicate error for both since the unique index is still there
//  So, even though being null, the unique index is still enforced by MongoDB, and it will not allow multiple documents with the same value including null